[sdl]
autolock=false
fullscreen=false
fulldouble=false
output=surface
sensitivity=100
waitonerror=false
usescancodes=true

[dosbox]
machine=svga_s3
captures=/work/dosbox/capture
memsize=16

[cpu]
core=auto
cputype=auto
cycles=auto

[mixer]
nosound=true

[render]
frameskip=0
aspect=false
scaler=none

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
oplmode=auto

[speaker]
pcspeaker=false

[dos]
xms=true
ems=true
umb=true

[autoexec]
echo off
mount c /game
c:
dq3
