; Issue #5 research-only adapter for the C candidate generated by
; tools/run_matching_rng_adapter.py. This is not original DQ3 source.
; BX -> stack argument; DX:AX -> remainder:quotient. See docs/25.
BITS 16
ORG 0x0400

    cmp bx, 0
    jne .nonzero
    mov dx, 0
    ret
.nonzero:
    push cx
    push bx
    push bp
    push si
    push di
    push es
    push ds
    push bx
    call 0x0500
    add sp, 2
    pop ds
    pop es
    pop di
    pop si
    pop bp
    pop bx
    pop cx
    ret
